window.SRM=(()=>{const r = s => s.trim().split(/\s+/).map(x => x === '.' ? '' : x);
const PT = ['9:00','9:50','10:50','11:40','12:30','1:20','2:10','3:10','4:00'];
const SECTIONS = {
 'III-ECE-A': { label:'III Year ECE-A', sem:'V Semester', venue:'IST 518/FN',
  subj:{
   A:['Discrete Mathematics','21MAB302T','New Faculty 3'],
   B:['Microprocessor, Microcontroller & Interfacing Techniques','21ECC301P','Dr. M. Manikandan'],
   C:['VLSI Design and Technology','21ECC303T','Dr. M. Jothi'],
   D:['System and Network on Chip','21ECE468T','Dr. V. Manikandan'],
   E:['Machine Learning for All','21CSO355T','Dr. J. Jencia'],
   F:['Community Connect','21GNP301L','Dr. V. Rajesh / Dr. V. Bharathi'],
   G:['Analytical and Logical Thinking Skills','21PDM301L','CDC / 625'],
   H:['Indian Art Form','21LEM301T','Dr. K. Vigneshwaran'],
   L:['VLSI Design / Microprocessor Laboratory','21ECC311L','Dr. M. Jothi, Dr. P. Murugapandiyan, Dr. V. Manikandan']},
  tt:{Mon:r('E B B A . G G . .'),Tue:r('H D B B . . G . .'),Wed:r('C A D F . . . L L'),Thu:r('A E C F . . . . .'),Fri:r('D A E C . L L . .')}},
 'III-ECE-B': { label:'III Year ECE-B', sem:'V Semester', venue:'IST 518/AN',
  subj:{
   A:['Discrete Mathematics','21MAB302T','Dr. M. Thanga Rejini'],
   B:['Microprocessor, Microcontroller & Interfacing Techniques','21ECC301P','Mrs. B. Abirami'],
   C:['VLSI Design and Technology','21ECC303T','Dr. R. Vinoth Raj'],
   D:['System and Network on Chip','21ECE468T','Dr. V. Manikandan'],
   E:['Machine Learning for All','21CSO355T','Dr. J. Jencia'],
   F:['Community Connect','21GNP301L','Dr. H. Sudharsan / Ms. T. Swetha'],
   G:['Analytical and Logical Thinking Skills','21PDM301L','CDC / 625'],
   H:['Indian Art Form','21LEM301T','Dr. A. Anand'],
   L:['VLSI Design / Microprocessor Laboratory','21ECC311L','Dr. Sreenivasa Ijada Rao, Dr. B. DeviSri, Dr. Prassanna Venkatesh']},
  tt:{Mon:r('L L . . . E B A D'),Tue:r('G G . . . F B D C'),Wed:r('G . . . . B B A H'),Thu:r('L L . . . A C E F'),Fri:r('. . . . . C A E D')}},
 'III-ECE-DS': { label:'III Year ECE-DS', sem:'V Semester', venue:'IST 519/FN',
  subj:{
   A:['Discrete Mathematics','21MAB302T','New Faculty 2'],
   B:['Microprocessor, Microcontroller & Interfacing Techniques','21ECC301P','Mrs. B. Abirami'],
   C:['VLSI Design and Technology','21ECC303T','Dr. R. Vinoth Raj'],
   D:['Machine Learning for All','21CSO355T','Dr. Chitra Devi'],
   E:['Database Design and Management','21ECE371T','Dr. S. Saraswathi'],
   F:['Community Connect','21GNP301L','Dr. S. Jeevanantham / Dr. V. Manikandan'],
   G:['Analytical and Logical Thinking Skills','21PDM301L','CDC / 625'],
   H:['Indian Art Form','21LEM301T','Dr. Prabin Kumar Bera'],
   L:['VLSI Design / Microprocessor Laboratory','21ECC311L','Dr. R. Vinothraj / Dr. H. Sri Bhuvaneshwari']},
  tt:{Mon:r('E B C A . . . . .'),Tue:r('C B D F . L L . .'),Wed:r('H B A C . . . G G'),Thu:r('A D E F . . . . .'),Fri:r('D A E B . G . L L')}},
 'III-BME': { label:'III Year BME', sem:'V Semester', venue:'IST 211/AN',
  subj:{
   A:['Probability and Statistics','21MAB301T','Dr. K. M. Karuppusamy'],
   B:['Microcontrollers and Its Application in Medicine','21BMC302J','Dr. K. Vigneshwaran'],
   C:['Biomedical Signal Processing','21BMC301J','Dr. V. N. Senthilkumaran'],
   D:['Biometrics','21BME266T','Dr. G. Gifta'],
   E:['Modern Wireless Communication System','21ECO103T','Dr. Vaishnavi'],
   F:['Principles of Medical Imaging','21BMC303T','Dr. N. Prasanna Venkatesh'],
   G:['Analytical and Logical Thinking Skills','21PDM301L','CDC / 625'],
   H:['Indian Art Form','21LEM301T','Dr. G. Gifta'],
   I:['Community Connect','21GNP301L','Dr. J. Jencia / Dr. N. Prasanna Venkatesh'],
   M:['MPMC Lab (Microcontrollers)','21BMC302J','Lab slot, LAB-107'],
   P:['Bio DSP Lab (Signal Processing)','21BMC301J','Lab slot, LAB-108']},
  tt:{Mon:r('G G M M . E B F H'),Tue:r('P P G . . C D A B'),Wed:r('. . . . . C A F D'),Thu:r('. . . I . A C E B'),Fri:r('I . . . . F A D E')}},
 'IV-ECE-A': { label:'IV Year ECE-A', sem:'VII Semester', venue:'IST 225',
  subj:{
   A:['Behavioural Psychology','21GNH401T','Dr. A. Anand'],
   B:['Wireless Communication and Antenna Systems','21ECC401T','Dr. K. Vigneshwaran'],
   C:['Computer Communication and Network Security','21ECC402P','Dr. S. Jeevanantham'],
   D:['Semiconductor Memory Design','21ECE461T','Dr. H. Sri Bhuvaneshwari'],
   E:['Scripting Language for Electronic Design Automation','21ECE463T','Dr. Sreenivasa Rao Ijada'],
   F:['Machine Learning for All','21CSO355T','Dr. N. Prasanna Venkatesh'],
   L:['Computer Communication and Network Security Lab','21ECC402P','Mrs. T. Swetha']},
  tt:{Mon:r('C . A D . . . . .'),Tue:r('C D B F . . . . .'),Wed:r('B L E F . . . . .'),Thu:r('F A E B . . . . .'),Fri:r('C A D E . . . . .')}},
 'IV-ECE-B': { label:'IV Year ECE-B', sem:'VII Semester', venue:'IST 227',
  subj:{
   A:['Behavioural Psychology','21GNH401T','Dr. A. Annand'],
   B:['Wireless Communication and Antenna Systems','21ECC401T','Dr. K. Vigneshwaran'],
   C:['Computer Communication and Network Security','21ECC402P','Dr. R. Rajasekar'],
   D:['Semiconductor Memory Design','21ECE461T','Dr. H. Sri Bhuvaneshwari'],
   E:['Scripting Language for Electronic Design Automation','21ECE463T','Dr. Sreenivasa Rao Ijada'],
   F:['Machine Learning for All','21CSO355T','Dr. N. Prasanna Venkatesh'],
   L:['Computer Communication and Network Security Lab','21ECC402P','Ms. T. Swetha']},
  tt:{Mon:r('C A E F . . . . .'),Tue:r('C E F B . . . . .'),Wed:r('C D A B . . . . .'),Thu:r('D B L A . . . . .'),Fri:r('E D F . . . . . .')}},
 'II-ECE-DS-B': { label:'II Year ECE-DS B', sem:'III Semester', venue:'IST 411/AN',
  subj:{
   A:['Transforms and Boundary Value Problems','21MAB201T','New Faculty 3'],
   B:['Solid State Devices','21ECC201T','Dr. S. Jeevanantham'],
   C:['Computer Organization and Architecture','21CSS201T','Dr. P. Murugapandiyan'],
   D:['Digital Logic Design','21ECC203T','Dr. S. Krishnakumar'],
   E:['Electromagnetic Theory and Interference','21ECC205T','Dr. V. Bharathi'],
   F:['Professional Ethics','21LEM201T','Dr. K. Vigneshwaran'],
   G:['Universal Human Values-II','21LEM202T','Mrs. D. Lavanya'],
   H:['Verbal Reasoning','21PDM201L','CDC / TB-106'],
   I:['Social Engineering','21PDH209T','Mrs. D. Lavanya'],
   L:['Devices and Digital IC Laboratory','21ECC211L','Dr. S. Krishnakumar']},
  tt:{Mon:r('. . L L . D B C I'),Tue:r('L L . . . C D E A'),Wed:r('G . . . . I E A D'),Thu:r('G G H H . A C B E'),Fri:r('H . . . . F A B C')}}
};

return {PT,SECTIONS}})();
